<a href="https://colab.research.google.com/github/MariamChowdhury/MachineLearning/blob/main/AlgorithmsAndClassifiers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np

# Multivarient linear regression

In [ ]:
pip install word2number

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from word2number import w2n

In [ ]:
print(w2n.word_to_num('two point three'))

2.3


In [ ]:
df=pd.read_csv('/content/hiring.csv')

In [ ]:
df

experience  score  int score  salary
0        NaN    8.0          9   50000
1        NaN    8.0          6   45000
2       five    6.0          7   60000
3        two   10.0         10   65000
4      seven    9.0          6   70000
5      three    7.0         10   62000
6        ten    NaN          7   72000
7     eleven    7.0          8   80000

In [ ]:
df.score.median()


8.0

In [ ]:
df.score = df.score.fillna(df.score.mean())

In [ ]:
df

experience  score  int score  salary
0           0    8.0          9   50000
1           0    8.0          6   45000
2           5    6.0          7   60000
3           2   10.0         10   65000
4           7    9.0          6   70000
5           3    7.0         10   62000
6          10    8.0          7   72000
7          11    7.0          8   80000

In [ ]:
df.experience = df.experience.fillna("zero")

In [ ]:
df

experience  score  int score  salary
0           0    8.0          9   50000
1           0    8.0          6   45000
2           5    6.0          7   60000
3           2   10.0         10   65000
4           7    9.0          6   70000
5           3    7.0         10   62000
6          10    8.0          7   72000
7          11    7.0          8   80000

In [ ]:
df.experience = df.experience.apply(w2n.word_to_num)

In [ ]:
df

experience  score  int score  salary
0           0    8.0          9   50000
1           0    8.0          6   45000
2           5    6.0          7   60000
3           2   10.0         10   65000
4           7    9.0          6   70000
5           3    7.0         10   62000
6          10    8.0          7   72000
7          11    7.0          8   80000

In [ ]:
X = df[['experience', 'score', 'int score']]
y = df['salary']
reg = LinearRegression().fit(X, y)

In [ ]:
reg.predict([[2, 9, 6]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([53205.96797671])

In [ ]:
reg.predict([[12, 10, 10]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([92002.18340611])

# Dummy variables

***Home Prices***

In [2]:
df=pd.read_csv('/content/price.csv')
df.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [3]:
dummy=pd.get_dummies(df.town)

In [4]:
dummy


monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [5]:
merged=pd.concat([dummy,df], axis='columns')

In [6]:
merged

monroe township  robinsville  west windsor             town  area   price
0                 1            0             0  monroe township  2600  550000
1                 1            0             0  monroe township  3000  565000
2                 1            0             0  monroe township  3200  610000
3                 1            0             0  monroe township  3600  680000
4                 1            0             0  monroe township  4000  725000
5                 0            0             1     west windsor  2600  585000
6                 0            0             1     west windsor  2800  615000
7                 0            0             1     west windsor  3300  650000
8                 0            0             1     west windsor  3600  710000
9                 0            1             0      robinsville  2600  575000
10                0            1             0      robinsville  2900  600000
11                0            1             0      robinsville  3100  620000
12                0            1             0      robinsville  3600  695000

In [7]:
df2=merged.drop(['town'], axis='columns')
df2

monroe township  robinsville  west windsor  area   price
0                 1            0             0  2600  550000
1                 1            0             0  3000  565000
2                 1            0             0  3200  610000
3                 1            0             0  3600  680000
4                 1            0             0  4000  725000
5                 0            0             1  2600  585000
6                 0            0             1  2800  615000
7                 0            0             1  3300  650000
8                 0            0             1  3600  710000
9                 0            1             0  2600  575000
10                0            1             0  2900  600000
11                0            1             0  3100  620000
12                0            1             0  3600  695000

In [8]:
final=df2.drop(['west windsor'], axis='columns')
final

monroe township  robinsville  area   price
0                 1            0  2600  550000
1                 1            0  3000  565000
2                 1            0  3200  610000
3                 1            0  3600  680000
4                 1            0  4000  725000
5                 0            0  2600  585000
6                 0            0  2800  615000
7                 0            0  3300  650000
8                 0            0  3600  710000
9                 0            1  2600  575000
10                0            1  2900  600000
11                0            1  3100  620000
12                0            1  3600  695000

In [10]:
X=final.drop(['price'], axis='columns')
X

monroe township  robinsville  area
0                 1            0  2600
1                 1            0  3000
2                 1            0  3200
3                 1            0  3600
4                 1            0  4000
5                 0            0  2600
6                 0            0  2800
7                 0            0  3300
8                 0            0  3600
9                 0            1  2600
10                0            1  2900
11                0            1  3100
12                0            1  3600

In [11]:
y=final.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [12]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [22]:
model.fit(X,y)

LinearRegression()

In [25]:
model.predict(X)

array([539709.73984089, 590468.71640507, 615848.20468716, 666607.18125135,
       717366.15781553, 579723.71533004, 605103.20361213, 668551.92431735,
       706621.15674049, 565396.1513653 , 603465.38378843, 628844.87207052,
       692293.59277575])

In [23]:
model.predict([[0,0,3400]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([681241.6684584])

In [24]:
model.score(X,y)

0.9573929037221874

***Car prices***

In [26]:
df3=pd.read_csv('/content/car.csv')
df3

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [33]:
car = pd.get_dummies(df3['Car Model'])

In [34]:
car

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [35]:
merged1=pd.concat([df3,car], axis='columns')
merged1

Car Model  Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  \
0                  BMW X5    69000          18000         6        0       1   
1                  BMW X5    35000          34000         3        0       1   
2                  BMW X5    57000          26100         5        0       1   
3                  BMW X5    22500          40000         2        0       1   
4                  BMW X5    46000          31500         4        0       1   
5                 Audi A5    59000          29400         5        1       0   
6                 Audi A5    52000          32000         5        1       0   
7                 Audi A5    72000          19300         6        1       0   
8                 Audi A5    91000          12000         8        1       0   
9   Mercedez Benz C class    67000          22000         6        0       0   
10  Mercedez Benz C class    83000          20000         7        0       0   
11  Mercedez Benz C class    79000          21000         7        0       0   
12  Mercedez Benz C class    59000          33000         5        0       0   

    Mercedez Benz C class  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0  
5                       0  
6                       0  
7                       0  
8                       0  
9                       1  
10                      1  
11                      1  
12                      1

In [37]:
df4=merged1.drop(['Car Model'], axis='columns')
df4

Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  Mercedez Benz C class
0     69000          18000         6        0       1                      0
1     35000          34000         3        0       1                      0
2     57000          26100         5        0       1                      0
3     22500          40000         2        0       1                      0
4     46000          31500         4        0       1                      0
5     59000          29400         5        1       0                      0
6     52000          32000         5        1       0                      0
7     72000          19300         6        1       0                      0
8     91000          12000         8        1       0                      0
9     67000          22000         6        0       0                      1
10    83000          20000         7        0       0                      1
11    79000          21000         7        0       0                      1
12    59000          33000         5        0       0                      1

In [38]:
final2=df4.drop(['Mercedez Benz C class'], axis='columns')
final2

Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6        0       1
1     35000          34000         3        0       1
2     57000          26100         5        0       1
3     22500          40000         2        0       1
4     46000          31500         4        0       1
5     59000          29400         5        1       0
6     52000          32000         5        1       0
7     72000          19300         6        1       0
8     91000          12000         8        1       0
9     67000          22000         6        0       0
10    83000          20000         7        0       0
11    79000          21000         7        0       0
12    59000          33000         5        0       0

In [40]:
X2=final2.drop(['Sell Price($)'], axis='columns')
y2=final2['Sell Price($)']

In [42]:
X2

Mileage  Age(yrs)  Audi A5  BMW X5
0     69000         6        0       1
1     35000         3        0       1
2     57000         5        0       1
3     22500         2        0       1
4     46000         4        0       1
5     59000         5        1       0
6     52000         5        1       0
7     72000         6        1       0
8     91000         8        1       0
9     67000         6        0       0
10    83000         7        0       0
11    79000         7        0       0
12    59000         5        0       0

In [43]:
y2

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [44]:
model2= LinearRegression()

In [45]:
model2.fit(X2,y2)

LinearRegression()

In [46]:
model2.predict(X2)

array([18705.2723644 , 35286.78445645, 24479.19112468, 41245.76426391,
       29882.98779056, 28023.6135243 , 30614.46818502, 21879.57266964,
       12182.34562104, 26183.72387884, 18929.31674102, 20409.80511857,
       30477.15426156])

In [50]:
model2.score(X2,y2)

0.9417050937281082

In [52]:
model2.predict([[45000,4,0,0]]) #Price of mercedez benz that is 4 yr old with mileage 45000

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([36991.31721061])

# One hot encoding

In [53]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [54]:
new_df = df
new_df.town = le.fit_transform(new_df.town)
new_df

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [56]:
X=new_df[['town','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [57]:
y=new_df.price.values

In [58]:
y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000])

In [59]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')

In [60]:
X = ct.fit_transform(X)
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [61]:
X = X[:,1:]
X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [62]:
model.fit(X,y)

LinearRegression()

In [63]:
model.predict([[0,1,3400]])

array([681241.6684584])

In [64]:
model.score(X,y)

0.9573929037221873