<a href="https://colab.research.google.com/github/MariamChowdhury/MachineLearning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import

In [1]:
# https://numpy.org/doc/stable/user/absolute_beginners.html
import numpy as np

# CRUD 

*Create*

In [18]:
#creating 2 random arrays 3 by 5
data = np.random.rand(2,3,5)
#creating arrays with 0 only
zeroes = np.zeros((2,2,2))
#creating a full array with a specific number 
full = np.full((2,2,2), 7)
#creating arrays with 1 only
ones = np.ones((2,2,2))

In [19]:
data

array([[[0.99162299, 0.23686154, 0.63280083, 0.0696828 , 0.22850046],
        [0.45583646, 0.34222679, 0.00246285, 0.45457106, 0.33385532],
        [0.70765803, 0.80024231, 0.65934155, 0.86086907, 0.32969526]],

       [[0.88706954, 0.97051455, 0.51986979, 0.85830189, 0.92717848],
        [0.83276533, 0.45529882, 0.31619456, 0.30521521, 0.99510056],
        [0.38784228, 0.20864437, 0.07385357, 0.60720639, 0.39074924]]])

In [21]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [22]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [23]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [25]:
#creating new arrays with values
list1=[1,2,3,4,5]
np.array(list1)
##1D array => 1[]

array([1, 2, 3, 4, 5])

In [26]:
type(list1)

list

In [27]:
type(np.array(list1))

numpy.ndarray

In [28]:
list2=[1,2,3,4,5]
list3=[1,2,3,4,5]
array2=np.array([list1,list2,list3])
array2 #2D array => 2[]

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

*Read*

In [29]:
data=np.random.rand(1,3,5)

In [30]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [31]:
shape

(1, 3, 5)

In [32]:
# r*c
size

15

In [33]:
types

dtype('float64')

In [34]:
data

array([[[0.05627218, 0.56373468, 0.04872591, 0.87169425, 0.54688701],
        [0.72563873, 0.67095214, 0.50124319, 0.8314535 , 0.9373052 ],
        [0.25694676, 0.01050432, 0.05147826, 0.09991672, 0.05033639]]])

In [35]:
# Slicing (check doc)
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [60]:
data[0][0][0] = 500

In [61]:
data

array([[[5.00000000e+02, 5.63734681e-01, 4.87259093e-02, 8.71694249e-01,
         5.46887008e-01],
        [7.25638732e-01, 6.70952138e-01, 5.01243185e-01, 8.31453499e-01,
         9.37305195e-01],
        [2.56946757e-01, 1.05043227e-02, 5.14782554e-02, 9.99167153e-02,
         5.03363874e-02]]])

*Update*

In [40]:
list1 = np.random.rand(5) 
list2 = np.random.rand(5) 

In [41]:
list1

array([0.41841745, 0.00950895, 0.45927659, 0.67955989, 0.7699797 ])

In [42]:
list2

array([0.34433957, 0.44049593, 0.79218965, 0.67909533, 0.5655207 ])

In [43]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [44]:
add

array([0.76275701, 0.45000488, 1.25146624, 1.35865522, 1.3355004 ])

In [45]:
sub

array([ 0.07407788, -0.43098698, -0.33291306,  0.00046456,  0.20445901])

In [46]:
div

array([1.21513032, 0.02158692, 0.57975585, 1.00068409, 1.36154116])

In [47]:
mult

array([0.14407768, 0.00418865, 0.36383416, 0.46148595, 0.43543946])

In [48]:
dot

1.4090259054450966

In [49]:
# Stat Functions (remember SAP LEMM)
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [51]:
list3=np.random.rand(3,5)

In [52]:
list3

array([[0.11356796, 0.18779587, 0.46804111, 0.94707916, 0.17336731],
       [0.09206319, 0.66542816, 0.55398044, 0.43540512, 0.81792656],
       [0.69533797, 0.19281966, 0.90537587, 0.29927435, 0.58176141]])

In [53]:
list3.reshape(5,3)

array([[0.11356796, 0.18779587, 0.46804111],
       [0.94707916, 0.17336731, 0.09206319],
       [0.66542816, 0.55398044, 0.43540512],
       [0.81792656, 0.69533797, 0.19281966],
       [0.90537587, 0.29927435, 0.58176141]])

In [54]:
list3.reshape(15,1)

array([[0.11356796],
       [0.18779587],
       [0.46804111],
       [0.94707916],
       [0.17336731],
       [0.09206319],
       [0.66542816],
       [0.55398044],
       [0.43540512],
       [0.81792656],
       [0.69533797],
       [0.19281966],
       [0.90537587],
       [0.29927435],
       [0.58176141]])

In [55]:
list3.reshape(15,3)

ValueError: ignored

*Delete*

In [62]:
data

array([[[5.00000000e+02, 5.63734681e-01, 4.87259093e-02, 8.71694249e-01,
         5.46887008e-01],
        [7.25638732e-01, 6.70952138e-01, 5.01243185e-01, 8.31453499e-01,
         9.37305195e-01],
        [2.56946757e-01, 1.05043227e-02, 5.14782554e-02, 9.99167153e-02,
         5.03363874e-02]]])

In [63]:
np.delete(data, 0, axis=1)

array([[[0.72563873, 0.67095214, 0.50124319, 0.8314535 , 0.9373052 ],
        [0.25694676, 0.01050432, 0.05147826, 0.09991672, 0.05033639]]])

# Others

In [64]:
array2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [65]:
array2[1:,:2]

array([[1, 2],
       [1, 2]])

In [67]:
#check doc
np.linspace(0,15,30)

array([ 0.        ,  0.51724138,  1.03448276,  1.55172414,  2.06896552,
        2.5862069 ,  3.10344828,  3.62068966,  4.13793103,  4.65517241,
        5.17241379,  5.68965517,  6.20689655,  6.72413793,  7.24137931,
        7.75862069,  8.27586207,  8.79310345,  9.31034483,  9.82758621,
       10.34482759, 10.86206897, 11.37931034, 11.89655172, 12.4137931 ,
       12.93103448, 13.44827586, 13.96551724, 14.48275862, 15.        ])

*Copy function and broadcasting*

In [69]:
array2[:2]=100

In [70]:
array2

array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [71]:
value=10
array2>value

array([ True,  True, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True])

*Check random distribution*


In [72]:
arrayNew=np.random.rand(5,5)

In [73]:
arrayNew

array([[0.92973846, 0.79180845, 0.5121014 , 0.61980292, 0.24965141],
       [0.66560846, 0.96355755, 0.21867609, 0.55222262, 0.43952558],
       [0.45605363, 0.10623417, 0.84517014, 0.48722117, 0.09574654],
       [0.62178087, 0.62578455, 0.89162294, 0.65534345, 0.43417911],
       [0.88986526, 0.56473803, 0.70741507, 0.44683611, 0.25491262]])

In [74]:
np.random.randint(0,100,10)

array([ 9, 74, 48, 37, 89, 52, 34, 62, 77, 76])

In [75]:
np.random.random_sample((2,5)) #2()=> remember!

array([[0.58757128, 0.13410828, 0.59185894, 0.8209573 , 0.44804572],
       [0.18754803, 0.40554974, 0.65349021, 0.16539276, 0.34981325]])