<a href="https://colab.research.google.com/github/MariamChowdhury/MachineLearning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import

In [1]:
import numpy as np

# Others

In [4]:
list1=[1,2,3,4,5]
np.array(list1)
type(np.array(list1))

numpy.ndarray

In [5]:
array1=np.array(list1)
type(array1)

numpy.ndarray

In [6]:
array1 #1D array => 1[]

array([1, 2, 3, 4, 5])

In [7]:
list2=[1,2,3,4,5]
list3=[1,2,3,4,5]
array2=np.array([list1,list2,list3])
array2 #2D array => 2[]

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [8]:
array2.shape

(3, 5)

In [9]:
array2.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 1],
       [2, 3, 4],
       [5, 1, 2],
       [3, 4, 5]])

In [10]:
array2.reshape(15,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [1],
       [2],
       [3],
       [4],
       [5],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [11]:
array2.reshape(15,3)

ValueError: ignored

In [12]:
array2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [13]:
array2[1:,:2]

array([[1, 2],
       [1, 2]])

In [14]:
array2=np.arange(0,15)

In [15]:
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
array2=np.arange(0,15, step=3)

In [ ]:
array2

In [ ]:
np.linspace(0,15,30)

Copy function and broadcasting

In [ ]:
array2[:2]=100

In [ ]:
array2

In [ ]:
value=10
array2>value

Check random distribution later


In [ ]:
arrayNew=np.random.rand(5,5)

In [ ]:
arrayNew

In [ ]:
np.random.randint(0,100,10)

In [ ]:
np.random.random_sample((2,5)) #2()=> remember!

# CRUD 

*Create*

In [2]:
arrayRandom=np.random.rand(2,3,4)

In [3]:
arrayRandom

array([[[0.80211436, 0.27482113, 0.01018891, 0.53651254],
        [0.28792245, 0.05927613, 0.87305872, 0.30572756],
        [0.29609484, 0.32964609, 0.07920667, 0.90126202]],

       [[0.04505812, 0.66468943, 0.28750462, 0.75420097],
        [0.37806938, 0.68040294, 0.10208704, 0.74914951],
        [0.38609001, 0.47044189, 0.39423006, 0.11071075]]])

*Read*

*Update*

*Delete*