<a href="https://colab.research.google.com/github/MariamChowdhury/MachineLearning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [15]:
list1=[1,2,3,4,5]
np.array(list1)
type(np.array(list1))

numpy.ndarray

In [16]:
array1=np.array(list1)
type(array1)

numpy.ndarray

In [17]:
array1 #1D array => 1[]

array([1, 2, 3, 4, 5])

In [18]:
list2=[1,2,3,4,5]
list3=[1,2,3,4,5]
array2=np.array([list1,list2,list3])
array2 #2D array => 2[]

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [19]:
array2.shape

(3, 5)

In [20]:
array2.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 1],
       [2, 3, 4],
       [5, 1, 2],
       [3, 4, 5]])

In [21]:
array2.reshape(15,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [1],
       [2],
       [3],
       [4],
       [5],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [22]:
array2.reshape(15,3)

ValueError: ignored

In [23]:
array2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [24]:
array2[1:,:2]

array([[1, 2],
       [1, 2]])

In [25]:
array2=np.arange(0,15)

In [26]:
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
array2=np.arange(0,15, step=3)

In [28]:
array2

array([ 0,  3,  6,  9, 12])

In [29]:
np.linspace(0,15,30)

array([ 0.        ,  0.51724138,  1.03448276,  1.55172414,  2.06896552,
        2.5862069 ,  3.10344828,  3.62068966,  4.13793103,  4.65517241,
        5.17241379,  5.68965517,  6.20689655,  6.72413793,  7.24137931,
        7.75862069,  8.27586207,  8.79310345,  9.31034483,  9.82758621,
       10.34482759, 10.86206897, 11.37931034, 11.89655172, 12.4137931 ,
       12.93103448, 13.44827586, 13.96551724, 14.48275862, 15.        ])

Copy function and broadcasting

In [30]:
array2[:2]=100

In [31]:
array2

array([100, 100,   6,   9,  12])

In [32]:
value=10
array2>value

array([ True,  True, False, False,  True])

Check random distribution later


In [34]:
arrayNew=np.random.rand(5,5)

In [35]:
arrayNew

array([[0.83028149, 0.40453181, 0.73016113, 0.79451862, 0.12932413],
       [0.55484482, 0.7368613 , 0.59934038, 0.30777349, 0.2325574 ],
       [0.93376457, 0.28086009, 0.1990146 , 0.13323923, 0.23516623],
       [0.11044373, 0.35823633, 0.38495889, 0.33695979, 0.29532951],
       [0.00175166, 0.45999712, 0.77361362, 0.87870328, 0.32840412]])

In [36]:
np.random.randint(0,100,10)

array([97, 79, 64, 62, 14, 30, 33, 64, 56, 57])

In [39]:
np.random.random_sample((2,5)) #2()=> remember!

array([[0.08944819, 0.06947094, 0.15455945, 0.42312004, 0.61789248],
       [0.46724114, 0.5198094 , 0.62313725, 0.62414397, 0.1245778 ]])