<a href="https://colab.research.google.com/github/MariamChowdhury/MachineLearning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
list1=[1,2,3,4,5]
np.array(list1)
type(np.array(list1))

numpy.ndarray

In [4]:
array1=np.array(list1)
type(array1)

numpy.ndarray

In [5]:
array1 #1D array => 1[]

array([1, 2, 3, 4, 5])

In [6]:
list2=[1,2,3,4,5]
list3=[1,2,3,4,5]
array2=np.array([list1,list2,list3])
array2 #2D array => 2[]

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [8]:
array2.shape

(3, 5)

In [10]:
array2.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 1],
       [2, 3, 4],
       [5, 1, 2],
       [3, 4, 5]])

In [11]:
array2.reshape(15,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [1],
       [2],
       [3],
       [4],
       [5],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [12]:
array2.reshape(15,3)

ValueError: ignored

In [14]:
array2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [17]:
array2[1:,:2]

array([[1, 2],
       [1, 2]])

In [19]:
array2=np.arange(0,15)

In [20]:
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
array2=np.arange(0,15, step=3)

In [23]:
array2

array([ 0,  3,  6,  9, 12])

In [27]:
np.linspace(0,15,30)

array([ 0.        ,  0.51724138,  1.03448276,  1.55172414,  2.06896552,
        2.5862069 ,  3.10344828,  3.62068966,  4.13793103,  4.65517241,
        5.17241379,  5.68965517,  6.20689655,  6.72413793,  7.24137931,
        7.75862069,  8.27586207,  8.79310345,  9.31034483,  9.82758621,
       10.34482759, 10.86206897, 11.37931034, 11.89655172, 12.4137931 ,
       12.93103448, 13.44827586, 13.96551724, 14.48275862, 15.        ])